services:
  anti-bruteforce:
    build:
      context: ..
      dockerfile: deployments/api.Dockerfile
    container_name: anti-bruteforce
    restart: unless-stopped
    ports:
      - "8888:8080"
      - "50051:50051"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:17
    container_name: postgres-anti-bruteforce
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-anti-bruteforce:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-anti-bruteforce: