// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: AntiBruteforce.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{2}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_AntiBruteforce_proto protoreflect.FileDescriptor

const file_AntiBruteforce_proto_rawDesc = "" +
	"\n" +
	"\x14AntiBruteforce.proto\x12\x05event\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fHelloRequest\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthcheckRequest\"-\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb6\x01\n" +
	"\x0eAntiBruteforce\x12H\n" +
	"\x05Hello\x12\x13.event.HelloRequest\x1a\x14.event.HelloResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/hello-world\x12Z\n" +
	"\vHealthcheck\x12\x19.event.HealthcheckRequest\x1a\x1a.event.HealthcheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/healthcheckB0Z.github.com/Romasmi/anti-bruteforce/pkg/api;apib\x06proto3"

var (
	file_AntiBruteforce_proto_rawDescOnce sync.Once
	file_AntiBruteforce_proto_rawDescData []byte
)

func file_AntiBruteforce_proto_rawDescGZIP() []byte {
	file_AntiBruteforce_proto_rawDescOnce.Do(func() {
		file_AntiBruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AntiBruteforce_proto_rawDesc), len(file_AntiBruteforce_proto_rawDesc)))
	})
	return file_AntiBruteforce_proto_rawDescData
}

var file_AntiBruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AntiBruteforce_proto_goTypes = []any{
	(*HelloRequest)(nil),        // 0: event.HelloRequest
	(*HelloResponse)(nil),       // 1: event.HelloResponse
	(*HealthcheckRequest)(nil),  // 2: event.HealthcheckRequest
	(*HealthcheckResponse)(nil), // 3: event.HealthcheckResponse
}
var file_AntiBruteforce_proto_depIdxs = []int32{
	0, // 0: event.AntiBruteforce.Hello:input_type -> event.HelloRequest
	2, // 1: event.AntiBruteforce.Healthcheck:input_type -> event.HealthcheckRequest
	1, // 2: event.AntiBruteforce.Hello:output_type -> event.HelloResponse
	3, // 3: event.AntiBruteforce.Healthcheck:output_type -> event.HealthcheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AntiBruteforce_proto_init() }
func file_AntiBruteforce_proto_init() {
	if File_AntiBruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AntiBruteforce_proto_rawDesc), len(file_AntiBruteforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AntiBruteforce_proto_goTypes,
		DependencyIndexes: file_AntiBruteforce_proto_depIdxs,
		MessageInfos:      file_AntiBruteforce_proto_msgTypes,
	}.Build()
	File_AntiBruteforce_proto = out.File
	file_AntiBruteforce_proto_goTypes = nil
	file_AntiBruteforce_proto_depIdxs = nil
}
