// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: AntiBruteforce.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{2}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CheckAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthRequest) Reset() {
	*x = CheckAuthRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthRequest) ProtoMessage() {}

func (x *CheckAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthRequest.ProtoReflect.Descriptor instead.
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{4}
}

func (x *CheckAuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CheckAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CheckAuthRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CheckAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthResponse) Reset() {
	*x = CheckAuthResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthResponse) ProtoMessage() {}

func (x *CheckAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthResponse.ProtoReflect.Descriptor instead.
func (*CheckAuthResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ClearRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRateRequest) Reset() {
	*x = ClearRateRequest{}
	mi := &file_AntiBruteforce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRateRequest) ProtoMessage() {}

func (x *ClearRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRateRequest.ProtoReflect.Descriptor instead.
func (*ClearRateRequest) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{6}
}

func (x *ClearRateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ClearRateRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ClearRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRateResponse) Reset() {
	*x = ClearRateResponse{}
	mi := &file_AntiBruteforce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRateResponse) ProtoMessage() {}

func (x *ClearRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AntiBruteforce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRateResponse.ProtoReflect.Descriptor instead.
func (*ClearRateResponse) Descriptor() ([]byte, []int) {
	return file_AntiBruteforce_proto_rawDescGZIP(), []int{7}
}

var File_AntiBruteforce_proto protoreflect.FileDescriptor

const file_AntiBruteforce_proto_rawDesc = "" +
	"\n" +
	"\x14AntiBruteforce.proto\x12\x05event\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fHelloRequest\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthcheckRequest\"-\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\x10CheckAuthRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"#\n" +
	"\x11CheckAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"8\n" +
	"\x10ClearRateRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x13\n" +
	"\x11ClearRateResponse2\xe6\x02\n" +
	"\x0eAntiBruteforce\x12H\n" +
	"\x05Hello\x12\x13.event.HelloRequest\x1a\x14.event.HelloResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/hello-world\x12Z\n" +
	"\vHealthcheck\x12\x19.event.HealthcheckRequest\x1a\x1a.event.HealthcheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/healthcheck\x12V\n" +
	"\tCheckAuth\x12\x17.event.CheckAuthRequest\x1a\x18.event.CheckAuthResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/auth/check\x12V\n" +
	"\tClearRate\x12\x17.event.ClearRateRequest\x1a\x18.event.ClearRateResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/clear-rateB0Z.github.com/Romasmi/anti-bruteforce/pkg/api;apib\x06proto3"

var (
	file_AntiBruteforce_proto_rawDescOnce sync.Once
	file_AntiBruteforce_proto_rawDescData []byte
)

func file_AntiBruteforce_proto_rawDescGZIP() []byte {
	file_AntiBruteforce_proto_rawDescOnce.Do(func() {
		file_AntiBruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AntiBruteforce_proto_rawDesc), len(file_AntiBruteforce_proto_rawDesc)))
	})
	return file_AntiBruteforce_proto_rawDescData
}

var file_AntiBruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_AntiBruteforce_proto_goTypes = []any{
	(*HelloRequest)(nil),        // 0: event.HelloRequest
	(*HelloResponse)(nil),       // 1: event.HelloResponse
	(*HealthcheckRequest)(nil),  // 2: event.HealthcheckRequest
	(*HealthcheckResponse)(nil), // 3: event.HealthcheckResponse
	(*CheckAuthRequest)(nil),    // 4: event.CheckAuthRequest
	(*CheckAuthResponse)(nil),   // 5: event.CheckAuthResponse
	(*ClearRateRequest)(nil),    // 6: event.ClearRateRequest
	(*ClearRateResponse)(nil),   // 7: event.ClearRateResponse
}
var file_AntiBruteforce_proto_depIdxs = []int32{
	0, // 0: event.AntiBruteforce.Hello:input_type -> event.HelloRequest
	2, // 1: event.AntiBruteforce.Healthcheck:input_type -> event.HealthcheckRequest
	4, // 2: event.AntiBruteforce.CheckAuth:input_type -> event.CheckAuthRequest
	6, // 3: event.AntiBruteforce.ClearRate:input_type -> event.ClearRateRequest
	1, // 4: event.AntiBruteforce.Hello:output_type -> event.HelloResponse
	3, // 5: event.AntiBruteforce.Healthcheck:output_type -> event.HealthcheckResponse
	5, // 6: event.AntiBruteforce.CheckAuth:output_type -> event.CheckAuthResponse
	7, // 7: event.AntiBruteforce.ClearRate:output_type -> event.ClearRateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AntiBruteforce_proto_init() }
func file_AntiBruteforce_proto_init() {
	if File_AntiBruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AntiBruteforce_proto_rawDesc), len(file_AntiBruteforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AntiBruteforce_proto_goTypes,
		DependencyIndexes: file_AntiBruteforce_proto_depIdxs,
		MessageInfos:      file_AntiBruteforce_proto_msgTypes,
	}.Build()
	File_AntiBruteforce_proto = out.File
	file_AntiBruteforce_proto_goTypes = nil
	file_AntiBruteforce_proto_depIdxs = nil
}
